# Generated by Django 4.2 on 2023-06-23 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Cliente')),
                ('telefono', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='MEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=150, verbose_name='Nombre del Producto')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion del Producto')),
                ('aroma', models.CharField(blank=True, max_length=150, null=True, verbose_name='Aroma')),
                ('color', models.CharField(blank=True, max_length=150, null=True, verbose_name='Color')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad Disponible')),
                ('peso_neto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Peso neto, ml/gr')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mea.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'MEA',
                'verbose_name_plural': 'MEA',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Fecha del pedido')),
                ('producto', models.CharField(blank=True, max_length=500, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total')),
                ('pago', models.BooleanField(default=True)),
                ('nota', models.CharField(blank=True, max_length=150, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mea.cliente', verbose_name='Cliente')),
                ('listado', models.ManyToManyField(blank=True, null=True, to='mea.mea', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
